#!/bin/bash
set -e

swift run -c release cat Tests/testdata/a.in | cmp -s Tests/testdata/a.out /dev/stdin
swift run -c release cat Tests/testdata/a.in Tests/testdata/b.in | cmp -s Tests/testdata/ab.out /dev/stdin

echo OK
